# Generated by Django 2.0.7 on 2019-03-21 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20190321_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=10)),
                ('response1', models.CharField(max_length=10)),
                ('question2', models.CharField(max_length=10)),
                ('response2', models.CharField(max_length=10)),
                ('question3', models.CharField(max_length=10)),
                ('response3', models.CharField(max_length=10)),
                ('question4', models.CharField(max_length=10)),
                ('response4', models.CharField(max_length=10)),
                ('question5', models.CharField(max_length=10)),
                ('response5', models.CharField(max_length=10)),
                ('question6', models.CharField(max_length=10)),
                ('response6', models.CharField(max_length=10)),
                ('question7', models.CharField(max_length=10)),
                ('response7', models.CharField(max_length=10)),
                ('question8', models.CharField(max_length=10)),
                ('response8', models.CharField(max_length=10)),
                ('question9', models.CharField(max_length=10)),
                ('response9', models.CharField(max_length=10)),
                ('question10', models.CharField(max_length=10)),
                ('response10', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
