# Generated by Django 2.0.7 on 2019-03-21 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20190321_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response1', models.CharField(max_length=10)),
                ('response2', models.CharField(max_length=10)),
                ('response3', models.CharField(max_length=10)),
                ('response4', models.CharField(max_length=10)),
                ('response5', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userquestionresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserQuestionResponse',
        ),
    ]
